<?php


namespace App\Form;

use App\Repository\PhonesRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;

class EstimationType extends AbstractType
{

    public function connectManager(EntityManagerInterface $em)
    {
        $phone = $em->getRepository(PhonesRepository::class);
        $phone->findAll();
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {

        parent::buildForm($builder, $options); // TODO: Change the autogenerated stub
        $builder->add('brand', ChoiceType::class)
            ->add('model', ChoiceType::class)
            ->add('capacity', ChoiceType::class, [
                'choices' => [
                    '64' => '64',
                    '128' => '128',
                    '256' => '256',
                    '512' => '512'
                ]
            ])
            ->add('color', ChoiceType::class)
            ->add('liquid_damage', ChoiceType::class, [
                'choices' => [
                    'oui' => 'oui',
                    'non' => 'non'
                ]
            ])
            ->add('screenCracks', ChoiceType::class, [
                'choices' => [
                    'oui' => 'oui',
                    'non' => 'non'
                ]
            ])
            ->add('casingCracks', ChoiceType::class, [
                'choices' => [
                    'oui' => 'oui',
                    'non' => 'non'
                ]
            ])
            ->add('batteryCracks', ChoiceType::class, [
                'choices' => [
                    'oui' => 'oui',
                    'non' => 'non'
                ]
            ])
            ->add('buttonCracks', ChoiceType::class, [
                'choices' => [
                    'oui' => 'oui',
                    'non' => 'non'
                ]
            ])
            ->add('submit', SubmitType::class)
        ;
    }
}
