<?php


namespace App\Form;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class MatriceType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        parent::buildForm($builder, $options); // TODO: Change the autogenerated stub
        $builder->add('matrice_field', FileType::class, [
            'label' => 'matrice (CSV)',
            'mapped' => false,
            'constraints' => [
                /*new File([
                    'mimeTypes' => 'text/csv',
                    'mimeTypesMessage' => 'Entrez le fichier CSV de la nouvelle matrice'
                ])*/
            ]
        ])
            ->add('submit', SubmitType::class);
    }
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
        ]);
    }
}
