<?php

namespace App\Form;

use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        parent::buildForm($builder, $options); // TODO: Change the autogenerated stub
        $builder->add('gender', ChoiceType::class, [
            'choices' => [
                'Monsieur' => 'Mr',
                'Madame' => 'Mme'
            ]
        ]);
        $builder->add('firstname', TextType::class, [
            'required' => true
        ]);
        $builder->add('lastname', TextType::class, [
            'required' => true
        ]);
        /*$builder->add('adress', TextType::class, [
            'required' => true
        ]);*/
        $builder->add('postcode', NumberType::class, [
            'required' => true
        ]);
        $builder->add('city', TextType::class, [
            'required' => true
        ]);
        $builder->add('password', PasswordType::class, [
            'required' => true
        ]);
        /*$builder->add('password2', PasswordType::class, [
            'required' => true
        ]);*/
        $builder->add('phone', NumberType::class, [
            'required' => true
        ]);
        $builder->add('mail', EmailType::class, [
            'required' => true
        ]);
        $builder->add('submit', SubmitType::class);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        parent::configureOptions($resolver); // TODO: Change the autogenerated stub
        $resolver->setDefaults([
            'data_class' => User::class
        ]);
    }
}
